In [3]:
# criar sequencia python
python_list = [i for i in range(1_000_000+1)]

## Tempo de execução: 0.107s
## Memória utilizada: 39.8 MiB

In [2]:
import numpy as np

In [5]:
numpy_array = np.arange(0, 1_000_000 + 1, dtype='int64')

print(numpy_array)

## Tempo de execução: 0.008s
## Memória utilizada: 7.5 MiB

[      0       1       2 ...  999998  999999 1000000]


In [6]:
# criando um array

arr = np.array([1,2,3,4,5])
print(f'Elementos: {arr}, Tipo dos elementos: {arr.dtype}, Tamanho do array: {arr.shape}')

Elementos: [1 2 3 4 5], Tipo dos elementos: int64, Tamanho do array: (5,)


In [7]:
# criando uma matriz
matrix = np.arange(1., 10.).reshape((3, 3))
print(matrix)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [10]:
import pandas as pd

In [9]:
pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
    --------------------------------------- 0.3/11.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.5 MB 390.1 kB/s eta 0:00:29
   - -------------------------------------- 0.5/11.5 MB 390.1 kB/s eta 0:00:29
   -- ------------------------------------- 0.8/11.5 MB 435.8 kB/s eta 0:00:25
   -- ------------------------------------- 0.8/11.5 MB 435.8 kB/s eta 0:00:25
   --- ------------------------------------ 1.0/11.5 MB 470.4 kB/s eta 0:00:23
   --- ------------------------------------ 1.0/11.5 MB 470.4 kB/s eta 0:00:23
   ---- ----------------------------